//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UploadRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UploadRes", typeof(UploadRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Image.
        /// </summary>
        public static string Artwork_Image {
            get {
                return ResourceManager.GetString("Artwork_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Status.
        /// </summary>
        public static string Artwork_Status {
            get {
                return ResourceManager.GetString("Artwork_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be the copyright owner to post an artwork.
        /// </summary>
        public static string copyright_error {
            get {
                return ResourceManager.GetString("copyright_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Cannot be Empty.
        /// </summary>
        public static string Empty_Error {
            get {
                return ResourceManager.GetString("Empty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image cannot be empty.
        /// </summary>
        public static string Image_cannot_be_empty {
            get {
                return ResourceManager.GetString("Image_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 5-12 Keywords.
        /// </summary>
        public static string keyword_lenght_error {
            get {
                return ResourceManager.GetString("keyword_lenght_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category and subject to help collectors find your work.
        /// </summary>
        public static string select_category_str {
            get {
                return ResourceManager.GetString("select_category_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select subject and category.
        /// </summary>
        public static string select_subject {
            get {
                return ResourceManager.GetString("select_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category &amp; Subject.
        /// </summary>
        public static string step1_next_click {
            get {
                return ResourceManager.GetString("step1_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string step10_next_click {
            get {
                return ResourceManager.GetString("step10_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string step10_pre_click {
            get {
                return ResourceManager.GetString("step10_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Status.
        /// </summary>
        public static string step2_next_click {
            get {
                return ResourceManager.GetString("step2_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string step2_pre_click {
            get {
                return ResourceManager.GetString("step2_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you the copyright owner of this artwork?.
        /// </summary>
        public static string step3_copyright_string {
            get {
                return ResourceManager.GetString("step3_copyright_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know how you&apos;d like to sell your artwork.
        /// </summary>
        public static string step3_detail {
            get {
                return ResourceManager.GetString("step3_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the original artwork for sale?.
        /// </summary>
        public static string step3_forsale_string {
            get {
                return ResourceManager.GetString("step3_forsale_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Image.
        /// </summary>
        public static string step3_next_click {
            get {
                return ResourceManager.GetString("step3_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category  &amp; Subject.
        /// </summary>
        public static string step3_pre_click {
            get {
                return ResourceManager.GetString("step3_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to make it available for prints?.
        /// </summary>
        public static string step3_print_avaible_string {
            get {
                return ResourceManager.GetString("step3_print_avaible_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which year did you create this artwork?.
        /// </summary>
        public static string step3_year_string {
            get {
                return ResourceManager.GetString("step3_year_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify your image to adjust how you want your artwork to display across the site..
        /// </summary>
        public static string step4_detail {
            get {
                return ResourceManager.GetString("step4_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediums, Materials, &amp; Styles.
        /// </summary>
        public static string step4_next_click {
            get {
                return ResourceManager.GetString("step4_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Status.
        /// </summary>
        public static string step4_pre_click {
            get {
                return ResourceManager.GetString("step4_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us more about your artwork.
        /// </summary>
        public static string step5_description {
            get {
                return ResourceManager.GetString("step5_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string step5_keywords {
            get {
                return ResourceManager.GetString("step5_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging your artwork with keywords allows collectors to find your artwork more easily. It’s best to enter simple, descriptive words that describe the key visual elements of the work, such as color, subject matter, and artistic style..
        /// </summary>
        public static string step5_keywords_detail {
            get {
                return ResourceManager.GetString("step5_keywords_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 5-12 Keywords.
        /// </summary>
        public static string step5_keywords_lable {
            get {
                return ResourceManager.GetString("step5_keywords_lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 1-5 Materials.
        /// </summary>
        public static string step5_materials {
            get {
                return ResourceManager.GetString("step5_materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 1-5 Mediums.
        /// </summary>
        public static string step5_mediums {
            get {
                return ResourceManager.GetString("step5_mediums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string step5_next_click {
            get {
                return ResourceManager.GetString("step5_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Image.
        /// </summary>
        public static string step5_pre_click {
            get {
                return ResourceManager.GetString("step5_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 1-5 Styles.
        /// </summary>
        public static string step5_styles {
            get {
                return ResourceManager.GetString("step5_styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediums, Materials &amp; Styles.
        /// </summary>
        public static string step5_title {
            get {
                return ResourceManager.GetString("step5_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string step6_next_click {
            get {
                return ResourceManager.GetString("step6_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string step6_pre_click {
            get {
                return ResourceManager.GetString("step6_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string step7_next_click {
            get {
                return ResourceManager.GetString("step7_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string step7_pre_click {
            get {
                return ResourceManager.GetString("step7_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string step8_next_click {
            get {
                return ResourceManager.GetString("step8_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string step8_pre_click {
            get {
                return ResourceManager.GetString("step8_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string step9_next_click {
            get {
                return ResourceManager.GetString("step9_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string step9_pre_click {
            get {
                return ResourceManager.GetString("step9_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an image file which is at least 1200 x 1500 pixels and less than 50MB..
        /// </summary>
        public static string upload_string {
            get {
                return ResourceManager.GetString("upload_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
